name = "satusaf-v2"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 Database Binding
[[d1_databases]]
binding = "DB" # Available as process.env.DB
database_name = "satusaf-db"
database_id = "d166ff4b-4118-44f9-94ab-39d725c7affb"
migrations_dir = "migrations"
